local utils = require("util")
local keymap = utils.keymap
local feedkeys = utils.feedkeys

keymap("<C-/>", "gcc", { remap = true, silent = true, desc = "Comment toggle" }, "n")
keymap("<C-/>", "gc", { remap = true, silent = true, desc = "Comment toggle" }, "v")
keymap("<leader>e", "<cmd>Oil<cr>", "Explorer")
keymap("<C-p>", function()
    require("fzf-lua").files({
        winopts = { width = 0.5, preview = { hidden = "hidden" } },
        fzf_opts = { ["--layout"] = "reverse-list" },
        formatter = "path.filename_first",
    })
end, "Fzf Files Finder")
keymap("<leader>o", function()
    require("fzf-lua").oldfiles({
        winopts = { width = 0.5, preview = { hidden = "hidden" } },
        cwd_only = true,
        fzf_opts = { ["--layout"] = "reverse-list" },
    })
end, "Fzf Oldfiles")
keymap("<C-f>", function()
    require("fzf-lua").live_grep({ fzf_opts = { ["--layout"] = "reverse-list" } })
end, "Fzf Live Grep")
keymap("<leader><space>", function()
    require("fzf-lua").buffers({
        winopts = { width = 0.5, preview = { hidden = "hidden" } },
        fzf_opts = { ["--layout"] = "reverse-list" },
    })
end, "Fzf buffers")
keymap("<leader>H", "<cmd>FzfLua helptags<cr>", "Fzf Helptags")
keymap("<C-k>", "<C-w>k", "Focus up split")
keymap("<C-l>", "<C-w>l", "Focus left split")
keymap("<C-j>", "<C-w>j", "Focus down split")
keymap("<C-h>", "<C-w>h", "Focus right split")
keymap("<A-h>", "<C-w><", "Resize <")
keymap("<A-l>", "<C-w>>", "Resize >")
keymap("<A-j>", "<C-w>-", "Resize -")
keymap("<A-k>", "<C-w>+", "Resize +")
keymap("<A-=>", "<C-w>=", "Reset splits sizes")
keymap("<leader>v", "<C-w>v<C-w>l", "New vertical split")
keymap("<leader>h", "<C-w>s<C-w>j", "New horizontal split")
keymap("<Esc>", "<cmd>noh<cr>", "Clear search highlights", "n")
keymap("<C-d>", "<C-d>zz", "Better scroll down")
keymap("<C-u>", "<C-u>zz", "Better scroll up")
keymap("n", "nzz", "Better jump next", "n")
keymap("]d", function()
    vim.diagnostic.goto_next()
    feedkeys("zz")
end, { desc = "Better jump next diagnostic", remap = true }, "n")
keymap("[d", function()
    vim.diagnostic.goto_prev()
    feedkeys("zz")
end, { desc = "Better jump prev diagnostic", remap = true }, "n")
keymap("J", ":m '>+1<CR>gv=gv", "Move line down", "v")
keymap("K", ":m '<-2<CR>gv=gv", "Move line up", "v")
keymap("<", "<gv", "Keep selection when indenting multiple lines", "v")
keymap(">", ">gv", "Keep selection when indenting multiple lines", "v")
keymap("J", ":m '>+1<CR>gv=gv", "Move line down", "v")
keymap("K", ":m '<-2<CR>gv=gv", "Move line up", "v")
keymap("gd", vim.lsp.buf.definition, "LSP: Goto definition", "n")
keymap("gr", vim.lsp.buf.references, "LSP: Goto definition", "n")
keymap("<leader>lr", vim.lsp.buf.rename, "LSP: Goto definition", "n")
keymap("<leader>la", "<cmd>Fzf lsp_code_actions<cr>", "LSP: Code actions")
keymap("<leader>ls", vim.lsp.buf.signature_help, "LSP: Signature help")
keymap("<C-s>", vim.lsp.buf.signature_help, "LSP: Signature help", "i")
keymap("K", vim.lsp.buf.hover, "LSP: Show hover message", "n")
keymap("<leader>df", vim.diagnostic.open_float, "LSP: Show diagnostic message", "n")
keymap("<leader>dl", vim.diagnostic.setqflist, "LSP: List diagnostics", "n")
keymap("<F1>", function()
    feedkeys(":SplitrunNew ")
end, "Splitrun")
keymap("<leader>tt", "<cmd>tabnew<cr><cmd>term<cr>", "Open terminal in a new tab")
keymap("<leader>tn", "<cmd>tabnew<cr>", "Open new tab")
keymap("<Esc>", "<C-\\><C-n>", "Terminal mode easy exit", "t")
keymap("]t", "<cmd>tabnext<cr>", "Tab next")
keymap("[t", "<cmd>tabprevious<cr>", "Tab previous")
keymap("<C-g>", "<cmd>LazyGit<cr>", "Lazygit")
keymap("<leader>w", [[yiw/<C-r>"<CR><C-o>]], "Search buffer with word under cursor", "n")
keymap("<leader>S", "<cmd>Spectre<cr>", "Project search & replace")
keymap("<leader>T", "<cmd>FzfLua awesome_colorschemes<cr>", "Fzf Themes")
keymap("<leader>cs", "<cmd>FzfLua colorschemes<cr>", "Colorscheme selector")
keymap("R", "<cmd>LspRestart<cr>", "LSP: Restart language server")
keymap("<leader>lf", function()
    require("conform").format({ async = true, lsp_fallback = true })
end, "LSP: Format buffer")
keymap("<leader>gh", "<cmd>Gitsigns preview_hunk<cr>", "Git hunk")
keymap("<leader>gb", "<cmd>Gitsigns blame<cr>", "Git blame")
keymap("<leader>gd", "<cmd>Gitsigns diffthis<cr>", "Git diff")
keymap("yig", ":%y<CR>", "Yank buffer", "n")
keymap("vig", "ggVG", "Visual select buffer", "n")
keymap("cig", ":%d<CR>i", "Change buffer", "n")
